#!/usr/bin/env bash
# SPDX-License-Identifier: BSD-3-Clause
# Copyright (c) 2025, Intel Corporation

echo 0 > /sys/kernel/debug/tracing/events/zswap/zswap_compress/enable
echo 0 > /sys/kernel/debug/tracing/events/zswap/zswap_decompress/enable
echo 0 > /sys/kernel/debug/tracing/events/zswap/zswap_batch_compress/enable
echo 0 > /sys/kernel/debug/tracing/events/zswap/zswap_batch_decompress/enable
echo 0 > /sys/kernel/debug/tracing/events/zswap/zswap_compress_len/enable
echo 0 > /sys/kernel/debug/tracing/events/zswap/zswap_batch_compress_len/enable

echo > /sys/kernel/debug/tracing/trace

echo 1 > /sys/kernel/debug/tracing/events/zswap/zswap_compress/enable
echo 1 > /sys/kernel/debug/tracing/events/zswap/zswap_decompress/enable
echo 1 > /sys/kernel/debug/tracing/events/zswap/zswap_batch_compress/enable
echo 1 > /sys/kernel/debug/tracing/events/zswap/zswap_batch_decompress/enable

# Set trace buffer on CPU 1 to 5GB:
echo 10485760 > /sys/kernel/debug/tracing/per_cpu/cpu1/buffer_size_kb

echo "Removing zswap hists"

# zswap_[de]compress
echo '!hist:keys=cpu.buckets=10:sort=cpu:size=8192' >> /sys/kernel/debug/tracing/events/zswap/zswap_compress/trigger
echo '!hist:keys=cpu.buckets=10:sort=cpu:size=8192' >> /sys/kernel/debug/tracing/events/zswap/zswap_decompress/trigger

# zswap_[de]compress_batch
echo '!hist:keys=cpu.buckets=10:sort=cpu:size=8192' >> /sys/kernel/debug/tracing/events/zswap/zswap_batch_compress/trigger
echo '!hist:keys=cpu.buckets=10:sort=cpu:size=8192' >> /sys/kernel/debug/tracing/events/zswap/zswap_batch_decompress/trigger

echo "Enabling zswap hists"

# zswap_[de]compress
echo 'hist:keys=cpu.buckets=10:sort=cpu:size=8192' >> /sys/kernel/debug/tracing/events/zswap/zswap_compress/trigger
echo 'hist:keys=cpu.buckets=10:sort=cpu:size=8192' >> /sys/kernel/debug/tracing/events/zswap/zswap_decompress/trigger

# zswap_[de]compress_batch
echo 'hist:keys=cpu.buckets=10:sort=cpu:size=8192' >> /sys/kernel/debug/tracing/events/zswap/zswap_batch_compress/trigger
echo 'hist:keys=cpu.buckets=10:sort=cpu:size=8192' >> /sys/kernel/debug/tracing/events/zswap/zswap_batch_decompress/trigger

